version: "3"

services:
  battleship_auth:
    image: battleship/updater:${TAG:-latest}
    restart: unless-stopped
    links:
      - db
    ports:
      - 3333:3333
      JWT_SECRET: ${BATTLESHIP_JWT_SECRET}
    build:
      context: .
      dockerfile: Dockerfile